spring:
  application:
    name: email-service
  config:
    import: optional:configserver:http://localhost:8888
management:
  endpoints:
    web:
      exposure:
        include: refresh
mail:
  integracao: 'OCI'